### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by failpunk** [corenova/kos#1]
The following links are all 404ing.

Why embrace KOS?
Managing Flows with kos CLI
Managing State
Using KOS with React

**Comment by saintkepha** [comment]
@failpunk - thanks Justin, I'm now finalizing the core library APIs and will be doing a full refresh of the documentation in a day or so with actual working examples.  I'll ping you once it's ready to go so you can start to play with it!

**Comment by saintkepha** [comment]
I've revamped documentation to capture most of the usage scenarios.  I still need to cover the developer's guide but will mark this issue closed for now. :-)

**Comment by saintkepha** [comment]
BTW, hope to see you at the meetup tomorrow!
