### ISSUE TITLE
Sync/listen is not working in cases

### ISSUE THREAD

**Issue by georgetsahaya** [corenova/kos#5]
Scenario:

1) Run kos in commandline using the command "kos -v sync"
2) Try sync connect using the command "sync/connect "localhost"" in kos prompt
3) Getting error as expected as no one is listening at 12345 yet
5) Start sync listen using the command "sync/listen "localhost""
6) Start another kos instance and try sync connect using "sync/connect "localhost"" - Not working and getting connection refused error. We get to this scenario only when there is no listeners

Issue 1:

The sync/listen should start working in step 5 - But it is not happening.

Issue 2:

Proper error must have been thrown if there is a issue in listening - (No other listeners are bound at 12345, so ideally fix for the issue 1 should lead to disappearance of this scenario for now.)

**Comment by georgetsahaya** [comment]
With git update it is running into a loop, which is a issue itself

**Comment by saintkepha** [comment]
@georgetsahaya - thanks for the reported issue.  

KOS should be *enhanced* to prevent the infinite loop scenario but it doesn't make sense for the instance to do **both** listen and connect to itself.

When you do `sync/connect "localhost"` at step 2, it's not a one time operation but the instance establishes a persistent connection state to keep re-trying to connect.  Perhaps we should revisit that behavior?  Maybe only retry if it established successfully at least once?

**Comment by georgetsahaya** [comment]
@saintkepha - I agree the current behavior is not doing both the listen and connect by the same kos instance. The defects are as a outcome of some unintended action by the developer. Kos should atleast throw relevant error instead of breaking itself. (Perhaps low priority one)

When you talk about the retry, how long the retry is going to happen? How to stop the retry from the programmers perspective?

**Comment by saintkepha** [comment]
The synchronization loop that can potentially form in a given network is something that needs to be handled in a general sense.  A loop within itself would be one of the sub cases.
